spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lecture-management-db
    username: postgres
    password: 1903
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
